name: My First Workflow

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  
  pull_request:
    branches: [ main ]
    paths-ignore: [.github/**]
  
  # schedule:
  #   - cron: '15 6 * * 0'
  
  workflow_dispatch:

jobs:
    
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event trigger: ${{ github.event.event_name }}"
          echo "branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0 # checkout the repo

      - name: List files
        run: |
          echo "files in repo: ${{ github.respository }}"
          tree

  Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Test
      steps:
        - run: echo 'Testing...in env Test'

  Load-Test:
      runs-on: ubuntu-latest
      if: github.event_name == 'workflow_dispatch'
      needs: Build
      environment: Load-Test
      steps:
        - run: |
            echo 'Testing...in env Load-Test'
            sleep 5
  
  Production:
      runs-on: ubuntu-latest
      needs: [Test, Load-Test]
      environment:
        name: Production
        url: https://writeabout.net
      if: github.event.inputs.environment == 'Production'
      steps:
        - run: |
            echo "deploy prod: step 1"
            sleep 5
        - run: |
            echo "deploy prod: step 2"
            sleep 5
        - run: |
            echo "deploy prod: step 3"
            sleep 5
        - run: |
            echo "deploy prod: step 4"
            sleep 5
