name: My First Workflow

on:
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  
  pull_request:
    branches: [ main ]
    paths-ignore: [.github/**]
  
  schedule:
    - cron: '15 6 * * 0'
  
  workflow_dispatch:

jobs:
    
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event trigger: ${{ github.event.event_name }}"
          echo "branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0 # checkout the repo

      - name: List files
        run: |
          echo "files in repo: ${{ github.respository }}"
          tree
            
