name: hello-world CI

on:
  push:
    branches: [ main ]
    paths: [ hello-world-action/** ]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3.3.0
      
      - name: run container action
        id: hello-action
        uses: ./hello-world-action
        with:
          who-to-greet: '@bossman'
      
      - name: output time
        run: echo "The time is ${{ steps.hello-action.outputs.time }}"