name: Reuse other workflows

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reuable.yml
    with:
      who-to-greet: 'your majesty'

  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - name: reuse
        run: echo "reuse output ${{ needs.call-workflow.outputs.current-time }}"
